### ISSUE TITLE
 warning rst-selector-parser > nearley > nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.

### ISSUE THREAD

**Issue by graingert** [aweary/rst-selector-parser#12]
see also: https://github.com/airbnb/enzyme/issues/1532

**Comment by graingert** [comment]
I think an upgrade to nearly-react is needed.

**Comment by graingert** [comment]
https://github.com/kach/nearley/pull/284

**Comment by aweary** [comment]
Looks like according to kach/nearley#284 they're not going to fix this. We have a pretty hard dependency on nearly, so there's not much we can do if they don't decide to fix it.

**Comment by patcheng** [comment]
Looks like it's been fixed in nearley@2.16.0
