### ISSUE TITLE
Looks like selectors doesn't like special characters in their name

### ISSUE THREAD

**Issue by SathishGovindaraju** [aweary/rst-selector-parser#9]
Look https://github.com/airbnb/enzyme/issues/1218 for the issue which I raised in enzyme.
It looks like you cant parse a class name which has special characters like `/` or `@`.

**Comment by ljharb** [comment]
That's because it's an invalid class name in browsers too.

**Comment by aweary** [comment]
@yash0087  See https://github.com/airbnb/enzyme/issues/1218#issuecomment-333881962, this is expected behavior.
